stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: whereabouts
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

containerization:
  stage: containerization
  tags:
    - moreillon
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Build the docker image
    - docker build -t ${DOCKER_IMAGE} .
    # Pushing image to registry
    - docker push ${DOCKER_IMAGE}
    # Cleanup
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deployment
  tags:
    - moreillon
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    # Pull latest image by restarting the deployment
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      # Obtained from GitLab
      namespace: ${KUBERNETES_NAMESPACE}
